USE [THITRACNGHIEM]
GO
CREATE OR ALTER PROCEDURE dbo.sp_CheckDuSoCauThi @MAMH NCHAR(5), @TRINHDO NCHAR(1), @SOCAUTHI SMALLINT AS
BEGIN
 SET NOCOUNT ON;
 IF @TRINHDO NOT IN ('A','B','C') OR @SOCAUTHI NOT BETWEEN 10 AND 100 THROW 50001,N'Dữ liệu kiểm tra số câu không hợp lệ.',1;
 DECLARE @THAP CHAR(1)=CASE @TRINHDO WHEN 'A' THEN 'B' WHEN 'B' THEN 'C' END,@DUNG INT=0,@THAPCOUNT INT=0,@MIN INT=CEILING(@SOCAUTHI*.7),@DU BIT=0;
 SELECT @DUNG=COUNT(*) FROM BODE WHERE RTRIM(MAMH)=RTRIM(@MAMH) AND TRINHDO=@TRINHDO;
 SELECT @THAPCOUNT=COUNT(*) FROM BODE WHERE RTRIM(MAMH)=RTRIM(@MAMH) AND TRINHDO=@THAP;
 SET @DU=CASE WHEN @TRINHDO='C' AND @DUNG>=@SOCAUTHI THEN 1 WHEN @TRINHDO IN ('A','B') AND @DUNG>=@MIN AND @DUNG+@THAPCOUNT>=@SOCAUTHI THEN 1 ELSE 0 END;
 SELECT @DU DuCau,CASE @DU WHEN 1 THEN N'Đủ câu hỏi để đăng ký thi.' ELSE N'Không đủ câu hỏi theo quy tắc 70% - 30%.' END ThongBao,@TRINHDO TrinhDo,@THAP TrinhDoThapHon,@SOCAUTHI SoCauYeuCau,@MIN SoCauToiThieuDungTrinhDo,@DUNG SoCauDungTrinhDo,@THAPCOUNT SoCauThapHon;
END
GO
CREATE OR ALTER PROCEDURE dbo.sp_DangKyThi @MAGV NCHAR(8),@MALOP NCHAR(15),@MAMH NCHAR(5),@TRINHDO CHAR(1),@NGAYTHI DATETIME,@LAN SMALLINT,@SOCAUTHI SMALLINT,@THOIGIAN SMALLINT AS
BEGIN
 SET NOCOUNT ON; SET XACT_ABORT ON;
 BEGIN TRY
  SET TRANSACTION ISOLATION LEVEL SERIALIZABLE; BEGIN TRAN;
  IF NOT EXISTS(SELECT 1 FROM GIAOVIEN WHERE RTRIM(MAGV)=RTRIM(@MAGV)) THROW 50002,N'Giảng viên không tồn tại.',1;
  IF NOT EXISTS(SELECT 1 FROM LOP WHERE RTRIM(MALOP)=RTRIM(@MALOP)) OR NOT EXISTS(SELECT 1 FROM MONHOC WHERE RTRIM(MAMH)=RTRIM(@MAMH)) THROW 50003,N'Lớp hoặc môn học không tồn tại.',1;
  IF @TRINHDO NOT IN ('A','B','C') OR @LAN NOT BETWEEN 1 AND 2 OR @SOCAUTHI NOT BETWEEN 10 AND 100 OR @THOIGIAN NOT BETWEEN 5 AND 60 OR @NGAYTHI<=GETDATE() THROW 50004,N'Dữ liệu đăng ký thi không hợp lệ.',1;
  IF EXISTS(SELECT 1 FROM GIAOVIEN_DANGKY WITH(UPDLOCK,HOLDLOCK) WHERE RTRIM(MALOP)=RTRIM(@MALOP) AND RTRIM(MAMH)=RTRIM(@MAMH) AND LAN=@LAN) THROW 50005,N'Đăng ký bị trùng lớp, môn học và lần thi.',1;
  IF EXISTS(SELECT 1 FROM GIAOVIEN_DANGKY WITH(UPDLOCK,HOLDLOCK) WHERE (RTRIM(MALOP)=RTRIM(@MALOP) OR RTRIM(MAGV)=RTRIM(@MAGV)) AND @NGAYTHI<DATEADD(MINUTE,THOIGIAN,NGAYTHI) AND DATEADD(MINUTE,@THOIGIAN,@NGAYTHI)>NGAYTHI) THROW 50006,N'Lịch thi chồng thời gian.',1;
  DECLARE @T TABLE(DuCau BIT,ThongBao NVARCHAR(200),TrinhDo CHAR(1),TrinhDoThapHon CHAR(1),SoCauYeuCau INT,SoCauToiThieuDungTrinhDo INT,SoCauDungTrinhDo INT,SoCauThapHon INT); INSERT @T EXEC sp_CheckDuSoCauThi @MAMH,@TRINHDO,@SOCAUTHI;
  IF NOT EXISTS(SELECT 1 FROM @T WHERE DuCau=1) THROW 50007,N'Không đủ câu hỏi theo quy tắc 70% - 30%.',1;
  INSERT GIAOVIEN_DANGKY VALUES(@MAGV,@MAMH,@MALOP,@TRINHDO,@NGAYTHI,@LAN,@SOCAUTHI,@THOIGIAN); COMMIT;
  SELECT 1 ThanhCong,N'Đăng ký thi thành công.' ThongBao;
 END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH
END
GO
CREATE OR ALTER PROCEDURE dbo.sp_SuaDangKyThi @MAGV NCHAR(8),@MAMH_CU NCHAR(5),@MALOP_CU NCHAR(15),@LAN_CU SMALLINT,@MAMH NCHAR(5),@MALOP NCHAR(15),@TRINHDO CHAR(1),@NGAYTHI DATETIME,@LAN SMALLINT,@SOCAUTHI SMALLINT,@THOIGIAN SMALLINT AS
BEGIN
 SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRY BEGIN TRAN;
 IF NOT EXISTS(SELECT 1 FROM GIAOVIEN_DANGKY WITH(UPDLOCK,HOLDLOCK) WHERE RTRIM(MAMH)=RTRIM(@MAMH_CU) AND RTRIM(MALOP)=RTRIM(@MALOP_CU) AND LAN=@LAN_CU AND RTRIM(MAGV)=RTRIM(@MAGV)) THROW 50008,N'Đăng ký không tồn tại hoặc không thuộc giảng viên.',1;
 IF NOT EXISTS(SELECT 1 FROM LOP WHERE RTRIM(MALOP)=RTRIM(@MALOP)) OR NOT EXISTS(SELECT 1 FROM MONHOC WHERE RTRIM(MAMH)=RTRIM(@MAMH)) OR @TRINHDO NOT IN ('A','B','C') OR @LAN NOT BETWEEN 1 AND 2 OR @SOCAUTHI NOT BETWEEN 10 AND 100 OR @THOIGIAN NOT BETWEEN 5 AND 60 THROW 50004,N'Dữ liệu cập nhật đăng ký thi không hợp lệ.',1;
 IF EXISTS(SELECT 1 FROM BAITHI b JOIN SINHVIEN s ON b.MASV=s.MASV WHERE RTRIM(s.MALOP)=RTRIM(@MALOP_CU) AND RTRIM(b.MAMH)=RTRIM(@MAMH_CU) AND b.LAN=@LAN_CU) OR EXISTS(SELECT 1 FROM BANGDIEM b JOIN SINHVIEN s ON b.MASV=s.MASV WHERE RTRIM(s.MALOP)=RTRIM(@MALOP_CU) AND RTRIM(b.MAMH)=RTRIM(@MAMH_CU) AND b.LAN=@LAN_CU) THROW 50009,N'Đăng ký đã phát sinh bài thi hoặc điểm.',1;
 IF @NGAYTHI<=GETDATE() THROW 50004,N'Ngày thi phải ở tương lai.',1;
 IF EXISTS(SELECT 1 FROM GIAOVIEN_DANGKY WHERE RTRIM(MAMH)=RTRIM(@MAMH) AND RTRIM(MALOP)=RTRIM(@MALOP) AND LAN=@LAN AND NOT(RTRIM(MAMH)=RTRIM(@MAMH_CU) AND RTRIM(MALOP)=RTRIM(@MALOP_CU) AND LAN=@LAN_CU)) THROW 50005,N'Đăng ký bị trùng.',1;
 IF EXISTS(SELECT 1 FROM GIAOVIEN_DANGKY WHERE (RTRIM(MALOP)=RTRIM(@MALOP) OR RTRIM(MAGV)=RTRIM(@MAGV)) AND NOT(RTRIM(MAMH)=RTRIM(@MAMH_CU) AND RTRIM(MALOP)=RTRIM(@MALOP_CU) AND LAN=@LAN_CU) AND @NGAYTHI<DATEADD(MINUTE,THOIGIAN,NGAYTHI) AND DATEADD(MINUTE,@THOIGIAN,@NGAYTHI)>NGAYTHI) THROW 50006,N'Lịch thi chồng thời gian.',1;
 DECLARE @T TABLE(DuCau BIT,ThongBao NVARCHAR(200),TrinhDo CHAR(1),TrinhDoThapHon CHAR(1),SoCauYeuCau INT,SoCauToiThieuDungTrinhDo INT,SoCauDungTrinhDo INT,SoCauThapHon INT); INSERT @T EXEC sp_CheckDuSoCauThi @MAMH,@TRINHDO,@SOCAUTHI; IF NOT EXISTS(SELECT 1 FROM @T WHERE DuCau=1) THROW 50007,N'Không đủ câu hỏi.',1;
 UPDATE GIAOVIEN_DANGKY SET MAMH=@MAMH,MALOP=@MALOP,TRINHDO=@TRINHDO,NGAYTHI=@NGAYTHI,LAN=@LAN,SOCAUTHI=@SOCAUTHI,THOIGIAN=@THOIGIAN WHERE RTRIM(MAMH)=RTRIM(@MAMH_CU) AND RTRIM(MALOP)=RTRIM(@MALOP_CU) AND LAN=@LAN_CU AND RTRIM(MAGV)=RTRIM(@MAGV); COMMIT; SELECT 1 ThanhCong,N'Cập nhật đăng ký thi thành công.' ThongBao;
 END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH
END
GO
CREATE OR ALTER PROCEDURE dbo.sp_XoaDangKyThi @MAGV NCHAR(8),@MAMH NCHAR(5),@MALOP NCHAR(15),@LAN SMALLINT AS
BEGIN
 SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRY BEGIN TRAN;
 IF NOT EXISTS(SELECT 1 FROM GIAOVIEN_DANGKY WITH(UPDLOCK,HOLDLOCK) WHERE RTRIM(MAMH)=RTRIM(@MAMH) AND RTRIM(MALOP)=RTRIM(@MALOP) AND LAN=@LAN AND RTRIM(MAGV)=RTRIM(@MAGV)) THROW 50008,N'Đăng ký không tồn tại hoặc không thuộc giảng viên.',1;
 IF EXISTS(SELECT 1 FROM BAITHI b JOIN SINHVIEN s ON b.MASV=s.MASV WHERE RTRIM(s.MALOP)=RTRIM(@MALOP) AND RTRIM(b.MAMH)=RTRIM(@MAMH) AND b.LAN=@LAN) OR EXISTS(SELECT 1 FROM BANGDIEM b JOIN SINHVIEN s ON b.MASV=s.MASV WHERE RTRIM(s.MALOP)=RTRIM(@MALOP) AND RTRIM(b.MAMH)=RTRIM(@MAMH) AND b.LAN=@LAN) THROW 50009,N'Đăng ký đã phát sinh bài thi hoặc điểm.',1;
 DELETE GIAOVIEN_DANGKY WHERE RTRIM(MAMH)=RTRIM(@MAMH) AND RTRIM(MALOP)=RTRIM(@MALOP) AND LAN=@LAN AND RTRIM(MAGV)=RTRIM(@MAGV); COMMIT; SELECT 1 ThanhCong,N'Xóa đăng ký thi thành công.' ThongBao;
 END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH
END
GO
