module.exports = {
  key: "bang-diem",
  icon: "fa-solid fa-square-poll-vertical",
  routeBase: "/bang-diem",
  tableName: "BANGDIEM",
  title: "Bang diem",
  pageTitle: "Bang diem thi",
  primaryKey: "MASV + MAMH + LAN",
  fields: [
    { name: "MASV", label: "Ma sinh vien", type: "nchar(8)", required: true, references: "SINHVIEN.MASV" },
    { name: "MAMH", label: "Ma mon hoc", type: "nchar(5)", required: true, references: "MONHOC.MAMH" },
    { name: "LAN", label: "Lan thi", type: "smallint", required: true },
    { name: "NGAYTHI", label: "Ngay thi", type: "date", required: false },
    { name: "DIEM", label: "Diem", type: "float", required: false },
  ],
  actions: ["list"],
  ownerHint: "Xem bang diem; chua cham diem hay ghi diem tu bai thi.",
  note: "Ket qua diem thi cua sinh vien theo mon hoc va lan thi.",
  gaps: ["SQL hien tai chua co bang luu chi tiet cau hoi da thi va cau tra loi cua sinh vien."],
};
