module.exports = {
  key: "bo-de",
  icon: "fa-solid fa-circle-question",
  routeBase: "/bo-de",
  tableName: "BODE",
  title: "Bo de",
  pageTitle: "Quan ly bo de",
  primaryKey: "CAUHOI",
  fields: [
    { name: "CAUHOI", label: "Cau hoi", type: "int", required: true },
    { name: "MAMH", label: "Ma mon hoc", type: "nchar(5)", required: false, references: "MONHOC.MAMH" },
    { name: "TRINHDO", label: "Trinh do", type: "char(1)", required: false, allowedValues: ["A", "B", "C"] },
    { name: "NOIDUNG", label: "Noi dung", type: "nvarchar(500)", required: false },
    { name: "A", label: "Dap an A", type: "nvarchar(200)", required: false },
    { name: "B", label: "Dap an B", type: "nvarchar(200)", required: false },
    { name: "C", label: "Dap an C", type: "nvarchar(200)", required: false },
    { name: "D", label: "Dap an D", type: "nvarchar(200)", required: false },
    { name: "DAP_AN", label: "Dap an dung", type: "char(1)", required: false, allowedValues: ["A", "B", "C", "D"] },
    { name: "MAGV", label: "Ma giao vien", type: "nchar(8)", required: false, references: "GIAOVIEN.MAGV" },
  ],
  actions: ["list", "create"],
  ownerHint: "CRUD bo de; phase sau moi rang buoc giao vien chi cap nhat cau hoi cua minh.",
  note: "Bo cau hoi trac nghiem theo mon hoc, trinh do va giao vien soan.",
  gaps: ["De bai ghi NOIDUNG nvarchar(200), SQL hien tai dung nvarchar(500). Tam thoi bam theo SQL."],
};
