module.exports = {
  key: "dang-ky-thi",
  icon: "fa-solid fa-calendar-check",
  routeBase: "/dang-ky-thi",
  tableName: "GIAOVIEN_DANGKY",
  title: "Dang ky thi",
  pageTitle: "Quan ly dang ky thi",
  primaryKey: "MAMH + MALOP + LAN",
  fields: [
    { name: "MAGV", label: "Ma giao vien", type: "nchar(8)", required: false },
    { name: "MAMH", label: "Ma mon hoc", type: "nchar(5)", required: true, references: "MONHOC.MAMH" },
    { name: "MALOP", label: "Ma lop", type: "nchar(15)", required: true, references: "LOP.MALOP" },
    { name: "TRINHDO", label: "Trinh do", type: "char(1)", required: false, allowedValues: ["A", "B", "C"] },
    { name: "NGAYTHI", label: "Ngay thi", type: "datetime", required: false },
    { name: "LAN", label: "Lan thi", type: "smallint", required: true },
    { name: "SOCAUTHI", label: "So cau thi", type: "smallint", required: false },
    { name: "THOIGIAN", label: "Thoi gian", type: "smallint", required: false },
  ],
  actions: ["list", "create"],
  ownerHint: "CRUD dang ky thi; phase sau moi kiem tra du cau hoi theo trinh do.",
  note: "Lich thi do giao vien dang ky cho lop va mon hoc.",
  gaps: ["De bai ghi THOIGIAN >= 5, SQL constraint hien tai >= 15. Tam thoi bam theo SQL."],
};
